# GCOOS DMAC Application Docker File
FROM robertdcurrier/tensorflow-gpu_python3:latest
MAINTAINER Bob Currier <robertdcurrier@gmail.com>
ENV REFRESHED_AT 2020-09-11

# Set the working directory to the name of the app /sban, /habscope, etc
WORKDIR /phytotracker3
# No requirements.txt -- all in the base image. This is the way of the Monkey.
ADD .vimrc /root/.vimrc
